### ISSUE TITLE
Fastlane description: minor adjustment suggested

### ISSUE THREAD

**Issue by IzzySoft** [ksh-b/raven#15]
Could you please add an empty line before the bullet-point list in your Fastlane's `full_description.txt`? That would make it render fine using standard Markdown then.

Thanks!

**Comment by ksh-b** [comment]
is it better now

**Comment by IzzySoft** [comment]
Thanks! Yes, that's fine now, so I'll enable pulling that along with future updates as well.

Btw: with your app [available in the IzzyOnDroid repo](https://apt.izzysoft.de/packages/kshib.raven/), you're welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme :smiley: In case you wonder: That's a repo with more than 1k Android FOSS apps, which folks can use with an [F-Droid client](https://android.izzysoft.de/applists/category/named/apps_markets#group_1181) of their choice (similar to the PlayStore app) to find apps, install them and keep them updated. Most of the clients also support other repos, like the one from [F-Droid](https://f-droid.org/) itself with more than 4k FOSS apps.
