### ISSUE TITLE
Add to fdroid oficially

### ISSUE THREAD

**Issue by Thewisem** [ksh-b/raven#17]
Adding to fdroid oficially would be great. Fdroid is a free and open source app store for opwn source enthusiasts. I think this would be a great addition to the app store

**Comment by ksh-b** [comment]
This is in progress
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14837

**Comment by Thewisem** [comment]
All the best :)

**Comment by Poussinou** [comment]
This was added
https://f-droid.org/packages/kshib.raven/

**Comment by Thewisem** [comment]
Thanks.
