### ISSUE TITLE
V0.12 Not Working

### ISSUE THREAD

**Issue by sanctimoniousape** [ksh-b/raven#21]
The new v0.12 doesn't load ***anything*** on a Pixel 7 Pro on Android 14, nor on OnePlus 7 Pro on Android 11.  I've cleared not just cache, but data as well.  I've tried all the alternate URLs & suggestions providers. I've disabled my local VPN ad-blocker.  I've waited a couple days to see if it was some temporary glitch. Nada.

**Comment by sanctimoniousape** [comment]
> I tested it on Moto G5 plus with Android 11 expecting to reproduce the issue but no luck. Neither there are issues on Pixel 7a with Android 14.

Well, if You've got some method of logging what it's doing so we can see where my devices are getting stuck, then please share how to do so.  Amy other advice on troubleshooting the issue is welcome.
 
> > I've tried all the alternate URLs & suggestions providers.
> 
> These options do not have anything to do with loading of articles.

I didn't think they did, but wanted to test all the possibilities in order to be sure that if tried everything I could to get it to work.

**Comment by ksh-b** [comment]
What subscriptions have you selected,
Is translation turned on

I asked the same question in your previous issue, but there was no response.

**Comment by ksh-b** [comment]
What subscriptions have you selected,
Is translation turned on

**Comment by ksh-b** [comment]
Continue in #19
