### ISSUE TITLE
Subscriptions page is cut off except on first run

### ISSUE THREAD

**Issue by sshockley** [ksh-b/raven#26]
When i view the subscriptions page, most of it is cut off.  It still scrolls like there are entries, but I can't click or select anything not visible.  If I uninstall/reinstall it works the first time it displays but not after that.

![Screenshot_20240518-150158](https://github.com/ksh-b/raven/assets/2092827/cebf384f-d9c0-4217-b559-465bc690b31a)

Only seems to affect all and technology pages.

Pixel 6 Pro, Android 14, May 2024 update.

**Comment by ksh-b** [comment]
Is the app version 0.12.2.
Should have been in fixed in that version. There was an issue when selecting Arstechina category.

**Comment by sshockley** [comment]
Fixed with update!  Thanks!
