### ISSUE TITLE
Unable to select text

### ISSUE THREAD

**Issue by GhostShadow0316** [ksh-b/raven#32]
https://github.com/ksh-b/raven/assets/94322065/88758569-948e-4c68-9d08-49fdb66a1b29

idk if it's designed to be like this
but this is pretty annoying specially for people not speaking English bc the translation experience is not good enough
and people might only not understanding one or two words in a sentence
maybe add a feature that while holding a word, it shows a pop-up or sth shows the translation of the word in user set language?

**Comment by ksh-b** [comment]
thats by default in flutter for some reason. fixed in 0.14.0
