### ISSUE TITLE
How do I add a custom URL?

### ISSUE THREAD

**Issue by Ejobat** [ksh-b/raven#39]
I've tried to add the custom URL `https://www.bbc.com/innovation`, but it's not working. When I try to add it to BBC, it doesn't show anything, nor does it get added.

Could you please help me understand how to properly add a custom URL like `https://www.bbc.com/innovation` to the categories? I'm not sure what I'm doing wrong, and I'd appreciate any guidance on the correct way to integrate a custom URL.

**Comment by ksh-b** [comment]
I have yet to add documentation on how to add custom URL. It is not possible with all sources. BBC is one of them.

An example for Reuters:
Say I want to add https://www.reuters.com/world/japan/

Custom URL would be `world/japan`

**Comment by Ejobat** [comment]
Thank you!
