### ISSUE TITLE
Can't Subcribe to Sources that are too lenghty

### ISSUE THREAD

**Issue by themrvideouser** [ksh-b/raven#6]
Cannot subscribe or scroll when category list is longer than screen size e.g. The Guardian

Expected: can scroll in Category Selection
Actual: can't scroll in Category Selection, which hinders me from saving selection e.g. when List is too long

Solution: make Category Selection scrollable

**Comment by ksh-b** [comment]
Fixed in [0.8.3](https://github.com/ksh-b/raven/releases/tag/v0.8.3)

**Comment by ksh-b** [comment]
closing as fixed, please reopen if needed
